server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ratingDb
    username: adempiere
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: RATING_SERVICE
eureka:
  instance:
    prefer-ip-address: true

  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
